/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	kriusdevv1alpha1 "github.com/viveksinghggits/krius/pkg/apis/krius.dev/v1alpha1"
	versioned "github.com/viveksinghggits/krius/pkg/client/clientset/versioned"
	internalinterfaces "github.com/viveksinghggits/krius/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/viveksinghggits/krius/pkg/client/listers/krius.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SekretInformer provides access to a shared informer and lister for
// Sekrets.
type SekretInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SekretLister
}

type sekretInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSekretInformer constructs a new informer for Sekret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSekretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSekretInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSekretInformer constructs a new informer for Sekret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSekretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KriusV1alpha1().Sekrets(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KriusV1alpha1().Sekrets(namespace).Watch(context.TODO(), options)
			},
		},
		&kriusdevv1alpha1.Sekret{},
		resyncPeriod,
		indexers,
	)
}

func (f *sekretInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSekretInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *sekretInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kriusdevv1alpha1.Sekret{}, f.defaultInformer)
}

func (f *sekretInformer) Lister() v1alpha1.SekretLister {
	return v1alpha1.NewSekretLister(f.Informer().GetIndexer())
}
