apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sekrets.krius.dev
spec:
  group: krius.dev
  names:
    kind: Sekret
    listKind: SekretList
    plural: sekrets
    singular: sekret
  scope: Namespaced
  subresources:
    status:
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            data:
              type: object
            type:
              type: string
      required:
      - metadata
      - apiVersion
      - spec
      - kind
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  additionalPrinterColumns:
  - name: Synced
    type: string
    JSONPath: .status.synced