/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/viveksinghggits/krius/pkg/apis/krius.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKonfigs implements KonfigInterface
type FakeKonfigs struct {
	Fake *FakeKriusV1alpha1
	ns   string
}

var konfigsResource = schema.GroupVersionResource{Group: "krius.dev", Version: "v1alpha1", Resource: "konfigs"}

var konfigsKind = schema.GroupVersionKind{Group: "krius.dev", Version: "v1alpha1", Kind: "Konfig"}

// Get takes name of the konfig, and returns the corresponding konfig object, and an error if there is any.
func (c *FakeKonfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Konfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(konfigsResource, c.ns, name), &v1alpha1.Konfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Konfig), err
}

// List takes label and field selectors, and returns the list of Konfigs that match those selectors.
func (c *FakeKonfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KonfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(konfigsResource, konfigsKind, c.ns, opts), &v1alpha1.KonfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KonfigList{ListMeta: obj.(*v1alpha1.KonfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.KonfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested konfigs.
func (c *FakeKonfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(konfigsResource, c.ns, opts))

}

// Create takes the representation of a konfig and creates it.  Returns the server's representation of the konfig, and an error, if there is any.
func (c *FakeKonfigs) Create(ctx context.Context, konfig *v1alpha1.Konfig, opts v1.CreateOptions) (result *v1alpha1.Konfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(konfigsResource, c.ns, konfig), &v1alpha1.Konfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Konfig), err
}

// Update takes the representation of a konfig and updates it. Returns the server's representation of the konfig, and an error, if there is any.
func (c *FakeKonfigs) Update(ctx context.Context, konfig *v1alpha1.Konfig, opts v1.UpdateOptions) (result *v1alpha1.Konfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(konfigsResource, c.ns, konfig), &v1alpha1.Konfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Konfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKonfigs) UpdateStatus(ctx context.Context, konfig *v1alpha1.Konfig, opts v1.UpdateOptions) (*v1alpha1.Konfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(konfigsResource, "status", c.ns, konfig), &v1alpha1.Konfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Konfig), err
}

// Delete takes name of the konfig and deletes it. Returns an error if one occurs.
func (c *FakeKonfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(konfigsResource, c.ns, name), &v1alpha1.Konfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKonfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(konfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KonfigList{})
	return err
}

// Patch applies the patch and returns the patched konfig.
func (c *FakeKonfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Konfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(konfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Konfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Konfig), err
}
