/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/viveksinghggits/krius/pkg/apis/krius.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSekrets implements SekretInterface
type FakeSekrets struct {
	Fake *FakeKriusV1alpha1
	ns   string
}

var sekretsResource = schema.GroupVersionResource{Group: "krius.dev", Version: "v1alpha1", Resource: "sekrets"}

var sekretsKind = schema.GroupVersionKind{Group: "krius.dev", Version: "v1alpha1", Kind: "Sekret"}

// Get takes name of the sekret, and returns the corresponding sekret object, and an error if there is any.
func (c *FakeSekrets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Sekret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sekretsResource, c.ns, name), &v1alpha1.Sekret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Sekret), err
}

// List takes label and field selectors, and returns the list of Sekrets that match those selectors.
func (c *FakeSekrets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SekretList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sekretsResource, sekretsKind, c.ns, opts), &v1alpha1.SekretList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SekretList{ListMeta: obj.(*v1alpha1.SekretList).ListMeta}
	for _, item := range obj.(*v1alpha1.SekretList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sekrets.
func (c *FakeSekrets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sekretsResource, c.ns, opts))

}

// Create takes the representation of a sekret and creates it.  Returns the server's representation of the sekret, and an error, if there is any.
func (c *FakeSekrets) Create(ctx context.Context, sekret *v1alpha1.Sekret, opts v1.CreateOptions) (result *v1alpha1.Sekret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sekretsResource, c.ns, sekret), &v1alpha1.Sekret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Sekret), err
}

// Update takes the representation of a sekret and updates it. Returns the server's representation of the sekret, and an error, if there is any.
func (c *FakeSekrets) Update(ctx context.Context, sekret *v1alpha1.Sekret, opts v1.UpdateOptions) (result *v1alpha1.Sekret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sekretsResource, c.ns, sekret), &v1alpha1.Sekret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Sekret), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSekrets) UpdateStatus(ctx context.Context, sekret *v1alpha1.Sekret, opts v1.UpdateOptions) (*v1alpha1.Sekret, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sekretsResource, "status", c.ns, sekret), &v1alpha1.Sekret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Sekret), err
}

// Delete takes name of the sekret and deletes it. Returns an error if one occurs.
func (c *FakeSekrets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sekretsResource, c.ns, name), &v1alpha1.Sekret{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSekrets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sekretsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SekretList{})
	return err
}

// Patch applies the patch and returns the patched sekret.
func (c *FakeSekrets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Sekret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sekretsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Sekret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Sekret), err
}
